version: "3.3"
services:
  flask:
    container_name: ni4os-webapp
    restart: always
    image: risojevicv/ni4osrssc_flask
    build:
        context: ./webapp
        dockerfile: Dockerfile
    ports:
      - "8080:80"
  tf_serving:
    container_name: rssc
    restart: always
    image: risojevicv/ni4osrssc_tf_serving
    build:
        context: ./service
        dockerfile: Dockerfile
    ports:
      - "8501:8501"
